### ISSUE TITLE
Finish gitpod setup

### ISSUE THREAD

**Issue by santanaluiz** [archway-network/archway-templates#10]
## Description

Need to setup Gitpod for templates

## TODO

- [ ] Config YAML file
- [ ] Create a new Docker image with archway-cli pre-installed
- [ ] Add it to the docs
